environment:
  node_version: '6.11.1'
  PATH: c:\tools\neovim\Neovim\bin;$(PATH)

install:
  - ps: Install-Product node $env:node_version
  - choco install neovim --pre -fy --ignoredependencies
  - npm install -g gulp
  - npm install

build_script:
  - gulp

test_script:
  - nvim --version
  - npm test --silent
