name: build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout VSCodeVim
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prettier
        if: matrix.os != 'windows-latest'
        run: yarn prettier:check

      - name: Lint
        if: matrix.os != 'windows-latest'
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test on ubuntu-latest
        if: matrix.os != 'windows-latest'
        run: |
          yarn build-test
          xvfb-run -a yarn test

      - name: Test on windows-latest
        if: matrix.os == 'windows-latest'
        run: |
          yarn build-test
          yarn test
